exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 88
indent-width = 4
target-version = "py311"

[lint]
select = [
    "B",     # Flake8 Bugbear
    "C4",    # Flake8 Comprehensions
    "DTZ",   # Flake8 Datatime
    "Q",     # Flake8 Quotes
    "I",     # Imports Sort
    "N",     # Pep8 Namespace
    "E",     # Pep8 Errors
    "W",     # Warning
    "D",     # Pydocstyle for docstring
    "F",     # Pyflakes
    "RUF",   # Ruff
]
ignore = ["D100", "D104", "D105", "D106", "D107", "D417"]


fixable = ["E", "W", "F", "B", "I", "N", "D"]
unfixable = []

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 72
