"""add uuid for user models.

Revision ID: c1cb93654ec0
Revises: 9abf2381bb1d
Create Date: 2025-03-30 19:45:42.640868

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1cb93654ec0"
down_revision: Union[str, None] = "9abf2381bb1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("uuid", sa.Uuid(), nullable=False))
    op.create_unique_constraint("uuid_unique", "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uuid_unique", "users", type_="unique")
    op.drop_column("users", "uuid")
    op.drop_column("profiles", "created_at")
    # ### end Alembic commands ###
