"""Create privilege table and association table for roles -> privileges.

Revision ID: 67cb2472f432
Revises: 7c2c301d2c85
Create Date: 2025-03-23 03:38:09.762999

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67cb2472f432"
down_revision: Union[str, None] = "7c2c301d2c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privileges",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles_privileges_associaton_table",
        sa.Column("roles_privileges_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("privilege_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["privilege_id"],
            ["privileges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("roles_privileges_id"),
        sa.UniqueConstraint(
            "role_id", "privilege_id", name="idx_unique_role_privilege"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_privileges_associaton_table")
    op.drop_table("privileges")
    # ### end Alembic commands ###
