"""update association tables with orm variation.

Revision ID: c59700bf726c
Revises: 67cb2472f432
Create Date: 2025-03-23 08:53:34.632393

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c59700bf726c"
down_revision: Union[str, None] = "67cb2472f432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "privileges",
        "name",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.add_column(
        "roles_privileges_associaton_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.alter_column(
        "roles_privileges_associaton_table",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text("now()"),
    )
    op.drop_column("roles_privileges_associaton_table", "roles_privileges_id")
    op.add_column(
        "users_roles_association_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.alter_column(
        "users_roles_association_table",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text("now()"),
    )
    op.drop_column("users_roles_association_table", "users_roles_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_roles_association_table",
        sa.Column("users_roles_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "users_roles_association_table",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        server_default=sa.text("now()"),
    )
    op.drop_column("users_roles_association_table", "id")
    op.add_column(
        "roles_privileges_associaton_table",
        sa.Column(
            "roles_privileges_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "roles_privileges_associaton_table",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        server_default=sa.text("now()"),
    )
    op.drop_column("roles_privileges_associaton_table", "id")
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "privileges",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
