"""update length field.

Revision ID: e065f8e92b24
Revises: 72fb27e548e5
Create Date: 2025-04-10 11:19:17.866166

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e065f8e92b24"
down_revision: Union[str, None] = "72fb27e548e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "name",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "surname",
        existing_type=sa.VARCHAR(length=35),
        type_=sa.String(length=40),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "surname",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=35),
        existing_nullable=True,
    )
    op.alter_column(
        "profiles",
        "name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=25),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
